### ISSUE TITLE
What cam job did you use?

### ISSUE THREAD

**Issue by kasbah** [UDXS/Arduitsy#1]
Hey, do you remember what CAM job you used to plot the Gerber and drill files? I wanted to recommend it to people for use with [kitnic.it](https://kitnic.it) because it actually produces drill files that are to spec.

**Comment by UDXS** [comment]
CAM Jobs are confusing to me so I ended up using Autodesk's eagle brd importer and then exporting the Gerber. You might be able to find what they used at circuits.io<http://circuits.io> or maybe you can ask them.

On May 26, 2017 12:29 AM, Kaspar Emanuel <notifications@github.com&

Hey, do you remember what CAM job you used to plot the Gerber and drill files? I wanted to recommend it to people for use with kitnic.it<https://kitnic.it> because it actually produces drill files that are to spec.
